[package]
name = "djam_4"
version = "0.1.0"
authors = ["Gnarwhal <gnarlynarwhal8@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.15.0"

[features]
default = ["vulkan"]
empty   = ["amethyst/empty"]
metal   = ["amethyst/metal"]
vulkan  = ["amethyst/vulkan"]